pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - "#approved-reviews-by>=2"
      - approved-reviews-by=@coretoolsteam
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=continuous-integration/travis-ci/pr
      - status-success=Continuous Integration / Formatting check (pull_request)
      - status-success=Continuous Integration / Analyzing code with Clippy (pull_request)
      - status-success=Continuous Integration / Tests (stable) (pull_request)
      - status-success=Continuous Integration / Tests (beta) (pull_request)
      - base=master
      - label!=dot_not_merge
      - label!=wip
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
