language: rust
cache: cargo
rust:
- stable
- beta
- nightly
env:
- PROJ_VERSION=6.1.0
before_install:
- wget https://github.com/OSGeo/proj.4/releases/download/${PROJ_VERSION}/proj-${PROJ_VERSION}.tar.gz
- tar -xzvf proj-${PROJ_VERSION}.tar.gz
- pushd proj-${PROJ_VERSION} && ./configure --prefix=/usr && make && sudo make install && popd
matrix:
  include:
  - rust: stable
    before_script: rustup component add rustfmt
    script: cargo fmt --all -- --check
  allow_failures:
  - rust: nightly
script:
- cargo test --verbose --features proj,transxchange
- cd model-builder && cargo test --verbose
deploy:
  provider: cargo
  on:
    tags: true
  token:
    secure: tkRGkfsZTG1whh17cWU1rAJRkMfuolBqUmhvR/ZXN/iULeDdSN0BQcukENU2V8BPVsWjX+eJvN9pdGeyt5jwhoT+1zFy/2aFWB75boVyExid7FXpVqyhlwo/XW+FB9FnW+Bnpgjjxvfx7fvGUTFQ4f/p3X8PiXkTh/o2iXg9AQiZiXMpJNdQtuiTUWX4Qh0cm6jly4cmBRqeaVTr4kXwtKEOS8S5r6gFMQ2kCsiIF5RDnzO2W9gWergLOQBxOFON1L+Oqzb6yyyTk0X/zur8HSqqn750z8p+Ysx+KfWw6FDrYAKGkAWgLjL3DqeyjmXnibg+++xuNV0qNGVnUCbMT7TMmyj34Yne10K0ChUSMpMdJFDDPTYdYzXJ2C2wuUuTHS36hy9eSwf0tJwjwZDJEL5xbSChHICC9W//DE29cpBGylkYuMqxeJRiIdYp6uFEyZBEXxiR+v4WNZ0Rxwp0TOO5jHbRADsZNTJRswrvArAj5WfvwU1z3MWIFIrG9xi5eQesQ+M0RCKd+zenmBFXRG4uADx7GQtNG7IpTPywufGIqYdUJY6A0VmB9yDlJB1uPygfkcHAIzB8Q2cCyml1txCBc/w2oWF6423h3QA8Jq25YOM29/qy8pb0btPWpnB+2045sD1OJObsNHrUT5Nium66A7HgtUDsTle1/B0/zWk=
