language: rust
rust:
  - stable
  - beta
addons:
  apt:
    sources:
    - sourceline: "deb [arch=amd64] https://kisiodigital.jfrog.io/kisiodigital/debian-local stretch main"
      key_url: "https://kisiodigital.jfrog.io/kisiodigital/api/gpg/key/public"
    packages:
    - proj=7.1.0
    - libxml2-utils
    - libtiff-dev
    - libcurl4-nss-dev
matrix:
  include:
  - rust: stable
    name: Formatting
    before_script: rustup component add rustfmt
    script: make format
  - rust: stable
    name: Linting
    before_script: rustup component add clippy
    script: make lint
script:
  - make test
