language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
  - rust: nightly
    before_script: cargo install rustfmt-nightly --force
    script: cargo fmt -- --write-mode diff
