[package]
name = "navitia_model"
version = "0.1.0"
authors = ["Kisio Digital <guillaume.pinot@kisio.org>"]

[workspace]

[dependencies]
derivative = "1"
serde = "1"
serde_derive = "1"
csv = "1.0.0-beta.5"
get-corresponding-derive = { path = "get-corresponding-derive" }

[dev-dependencies]
serde_json = "1"
