[package]
name = "navitia_model"
version = "0.1.0"
authors = ["Kisio Digital <guillaume.pinot@kisio.org>"]

[workspace]

[dependencies]
derivative = "1"
serde = "1"
serde_derive = "1"
csv = "1.0.0-beta.5"
log = "0.4"
get-corresponding-derive = { path = "get-corresponding-derive" }
chrono = "0.4.0"

[dev-dependencies]
tempdir = "0.3.5"
serde_json = "1"
env_logger = "0.5.0-rc.1"
